### ISSUE TITLE
Projekt widoku kalendarza

### ISSUE THREAD

**Issue by cesarzb** [Szade-Organization/BetterCalendar-Front#10]
Zaprojektować w figmie widok layoutu, czyli stałego układu aplikacji po zalogowaniu użytkownika (navbar, podział na aplikacji na kolumny), z wydzielonym miejscem na obecnie uruchomiony komponent.

**Comment by lodusm** [comment]
https://www.figma.com/file/VBArsfTFjxbHvlrSYEtCdD/BetterCalendar?type=design&node-id=0%3A1&mode=design&t=Rm5nzm9ARcf2a5Qr-1
