### ISSUE TITLE
Poprawić sposób automatycznego tworzenia kontenera projektu

### ISSUE THREAD

**Issue by WojciechSzade** [Szade-Organization/BetterCalendar-Front#20]
Repozytorium nazywa się BetterCalendar-Front, a obrazek dockerowy jest dystrybuowany pod nazwą better-calendar-react.  
Ujednolićcie to proszę, żeby wszędzie stosować tą samą nazwę dla łatwości użytkowania.

**Comment by cesarzb** [comment]
Zmiana, ponieważ należy jeszcze wprowadzić pewne dodatkowe zmiany w działaniu workflow Github Actions:
- zmiana nazwy kontenera aby pasował do nazwy repozytorium
- zmiana momentu w którym workflow jest aktywowany, tak aby był uruchamiany tylko kiedy merge'ujemy brach z main (czyli zmiany wprowadzone na branchu zostały już w jakiś sposób zatwierdzone jako poprawne), a nie za każdym razem gdy tworzony jest pull request.
Obecnie obraz dockerowy jest tworzony nawet dla potencjalnie niestabilnej wersji.
